
server:
  port: 8080
spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/order/**
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/product/**
